#!/usr/bin/env python

import csv
import os
import sqlite3
import sys
import yaml

if len(sys.argv) < 2 :
  print("""
usage: lgtExporter <configPath>

where <configPath> is the YAML configuration file defining what labels
database to export.

""")
  sys.exit(1)

# see: https://stackoverflow.com/a/1181922
alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

def int2tag(tagInt) :
  tagStr = ''
  while tagInt != 0 :
    tagInt, i = divmod(tagInt, 36)
    tagStr = alphabet[i] + tagStr
  while len(tagStr) < 4 :
    tagStr = '0' + tagStr
  return tagStr

config = {}
with open(sys.argv[1]) as yamlFile :
  config = yaml.safe_load(yamlFile.read())

if 'baseDir' not in config :  config['baseDir'] = '~'
baseDir = os.path.abspath(os.path.expanduser(config['baseDir']))

if 'dbPath' not in config :
  print("no dbPath specified in configuration")
  sys.exit(1)

dbPath = config['dbPath'].replace('$baseDir', baseDir)
dbName = os.path.basename(dbPath).split('.')[0]

tagsPath = f'{dbName}.tags'
if 'tagsPath' in config :
  tagsPath = config['tagsPath'].replace("$baseDir", baseDir)

tagsFile = open(tagsPath, "w")

labelsPath = f"{dbName}.labels"
if 'labelsPath' in config :
  labelsPath = config['labelsPath'].replace("$baseDir", baseDir)

labelsFile = open(labelsPath, "w", newline='')
labelsWriter = csv.writer(labelsFile, quoting=csv.QUOTE_ALL)

db = sqlite3.connect(dbPath)
dbCursor = db.cursor()

rows = dbCursor.execute("SELECT * FROM labels ORDER BY tag ASC")
for aRow in rows:
  labelsWriter.writerow(aRow)
  tagsFile.write(f"{int2tag(aRow[0])},{aRow[1]}\n")

db.close()
labelsFile.close()
tagsFile.close()
